import turtle
turtle.lt(75)
turtle.forward(100)
turtle.rt(150)
turtle.forward(50)
turtle.setheading(180)
turtle.forward(30)
turtle.back(30)
turtle.lt(105)
turtle.forward(50)
turtle.pu()
turtle.setheading(0)
turtle.forward(50)
turtle.pd()

