import turtle

turtle.pu()
turtle.fd(50)
turtle.pd()
turtle.circle(50,-180)
turtle.pu()
turtle.setheading(90)
turtle.bk(100)
turtle.pd()
turtle.fd(50)
turtle.setheading(180)
turtle.fd(20)
turtle.pu()
turtle.setheading(270)
turtle.fd(50)
turtle.setheading(0)
turtle.fd(50)
turtle.pd()
