import turtle
turtle.lt(90)
turtle.fd(100)
turtle.bk(50)
turtle.setheading(0)
turtle.lt(60)
turtle.fd(60)
turtle.bk(60)
turtle.setheading(0)
turtle.rt(60)
turtle.fd(60)
turtle.bk(60)
turtle.setheading(270)
turtle.fd(50)
turtle.setheading(0)
turtle.pu()
turtle.fd(75)
turtle.pd()
