import turtle 
turtle.circle(50)
turtle.pu()
turtle.setheading(270)
turtle.fd(10)
turtle.setheading(0)
turtle.fd(10)
turtle.lt(105)
turtle.pd()
turtle.fd(30)
turtle.bk(30)
turtle.pu()
turtle.setheading(90)
turtle.fd(10)
turtle.setheading(0)
turtle.fd(50)
turtle.pd()
