import turtle

turtle.setheading(90)
turtle.pu()
turtle.fd(100)
turtle.setheading(0)
turtle.rt(60)
turtle.pd()
turtle.fd(120)
turtle.setheading(0)
turtle.lt(60)
turtle.fd(60)
turtle.setheading(0)
turtle.rt(60)
turtle.fd(60)
turtle.setheading(0)
turtle.lt(60)
turtle.fd(120)
turtle.bk(120)
turtle.setheading(0)
turtle.pu()
turtle.fd(100)
turtle.pd()