import turtle
turtle.pu()
turtle.lt(90)
turtle.fd(100)
turtle.pd()
turtle.setheading(0)
turtle.fd(40)
turtle.rt(110)
turtle.fd(120)
turtle.setheading(0)
turtle.fd(40)
turtle.pu()
turtle.fd(50)
turtle.pd()